# List services *except* Render Postgres databases here
services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    name: metagame-bp
    repo: https://github.com/StephenBarlow/metagame # Default: Repo containing render.yaml
    numInstances: 1 # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: standard # Default: starter
    branch: master # Default: master
    buildCommand: npm install
    preDeployCommand: npm run migrate
    startCommand: npm run start
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default:
    envVars: # Environment variables
      - key: APP_SECRET
        generateValue: true # Generate a base64-encoded 256-bit value
