name: Render CLI Deploy
run-name: Deploying via Render CLI
on: [push]
jobs:
  Deploy-Render:
      runs-on: ubuntu-latest
      steps:
        - name: Install Render CLI
          # Download the Render CLI binary and add it to PATH
          # Note that we install a specific CLI version to prevent breaking changes
          run: |
            curl -L https://github.com/render-oss/cli/releases/download/v0.8.6/cli_0.8.6_linux_amd64.zip -o render.zip
            unzip render.zip
            sudo mv cli_v0.8.6 /usr/local/bin/render
        - name: Authorize Render CLI and trigger deploy
          env:
            RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
            CI: true
          run: |
            render login --output json
            render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm
